#    新建一个库，此文件路径为   .github/workflows/sunert-sync.yml，   然后新建分支main   
#    打开教程链接   https://www.jianshu.com/p/bb82b3ad1d11   申请PAT  （勾选时尽量全部勾选 ），填入secrets      手动运行或者定时运行即可同步

name: sunert-sync
on:
  schedule:
    - cron: '1 1 1 1 *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Maomaoyu0319-Sunert-1
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Maomaoyu0319-Sunert-1
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Maomaoyu0319/Sunert-1.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
